// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  queryURI: 'http://hapi.fhir.org/baseR4',
  testData:{
    "resourceType": "Bundle",
    "id": "6e349e47-4e6e-4ed0-a9cf-4d08692011cd",
    "meta": {
      "lastUpdated": "2020-05-26T03:29:56.518+00:00"
    },
    "type": "searchset",
    "link": [ {
      "relation": "self",
      "url": "http://hapi.fhir.org/baseR4/Patient"
    }, {
      "relation": "next",
      "url": "http://hapi.fhir.org/baseR4?_getpages=6e349e47-4e6e-4ed0-a9cf-4d08692011cd&_getpagesoffset=20&_count=20&_pretty=true&_bundletype=searchset"
    } ],
    "entry": [ {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL165-746-263",
      "resource": {
        "resourceType": "Patient",
        "id": "NL165-746-263",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:39:32.056+00:00",
          "source": "#22EHTjUnIjO1vcIC",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL165-746-263"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Inga Kuiper",
          "family": "Kuiper",
          "given": [ "Inga" ]
        }, {
          "use": "maiden",
          "text": "Inga Dekker",
          "family": "Dekker",
          "given": [ "Inga" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "ingakuiper@gmx.net",
          "use": "home",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1950-02-01",
        "address": [ {
          "text": "4381 Vlissingen, Paleisstraat 877",
          "line": [ "Paleisstraat 877" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4381",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL257-654-205",
      "resource": {
        "resourceType": "Patient",
        "id": "NL257-654-205",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:40:34.522+00:00",
          "source": "#lEeB83qys2Xn40ct",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL257-654-205"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Aadi Wolfs",
          "family": "Wolfs",
          "given": [ "Aadi" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "aadi@wolfs.NL",
          "use": "home",
          "rank": 1
        }, {
          "system": "email",
          "value": "aadiwolfs@trashmail.com",
          "use": "home",
          "rank": 2
        }, {
          "system": "phone",
          "value": "+31 065 670 5226",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "male",
        "birthDate": "1969-02-12",
        "address": [ {
          "text": "4338 Middelburg, Bloemsingel 668",
          "line": [ "Bloemsingel 668" ],
          "city": "Middelburg",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4338",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL858-395-453",
      "resource": {
        "resourceType": "Patient",
        "id": "NL858-395-453",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:41:37.027+00:00",
          "source": "#8lNMy5tsxD7iLPUU",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL858-395-453"
        } ],
        "active": false,
        "name": [ {
          "use": "official",
          "text": "Roelof van Vliet",
          "family": "van Vliet",
          "given": [ "Roelof" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "roelofvanvliet@trashmail.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 118 671 1601",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 065 419 2920",
          "use": "mobile",
          "rank": 2
        } ],
        "gender": "male",
        "birthDate": "1962-10-28",
        "address": [ {
          "text": "4336 Middelburg, Kerkweg 984",
          "line": [ "Kerkweg 984" ],
          "city": "Middelburg",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4336",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL295-868-464",
      "resource": {
        "resourceType": "Patient",
        "id": "NL295-868-464",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:42:39.520+00:00",
          "source": "#CRzQkwcd67Qb8v0W",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL295-868-464"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Maik Janssen",
          "family": "Janssen",
          "given": [ "Maik" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "maik@janssen.NL",
          "use": "home",
          "rank": 1
        }, {
          "system": "email",
          "value": "maikjanssen@lycos.com",
          "use": "home",
          "rank": 2
        } ],
        "gender": "male",
        "birthDate": "1952-06-02",
        "address": [ {
          "text": "4336 Middelburg, Tuinbeurs 938",
          "line": [ "Tuinbeurs 938" ],
          "city": "Middelburg",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4336",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL140-829-284",
      "resource": {
        "resourceType": "Patient",
        "id": "NL140-829-284",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:43:41.967+00:00",
          "source": "#RwQBRa4FwVogtftr",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL140-829-284"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Ilse Koster",
          "family": "Koster",
          "given": [ "Ilse" ]
        }, {
          "use": "maiden",
          "text": "Ilse Raven",
          "family": "Raven",
          "given": [ "Ilse" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "ilsekoster.92@outlook.com",
          "use": "work",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 064 104 3245",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1956-04-24",
        "address": [ {
          "text": "4371 Koudekerke, Prinsepoort 68",
          "line": [ "Prinsepoort 68" ],
          "city": "Koudekerke",
          "district": "Gemeente Veere",
          "state": "Zeeland",
          "postalCode": "4371",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL875-938-592",
      "resource": {
        "resourceType": "Patient",
        "id": "NL875-938-592",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:44:45.821+00:00",
          "source": "#qvGeEKQWV0hlFFxH",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL875-938-592"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Heyo van Riel",
          "family": "van Riel",
          "given": [ "Heyo" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "heyovanriel.2008@gmail.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 062 178 7040",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "male",
        "birthDate": "2008-07-30",
        "address": [ {
          "text": "Dauwendaele, Noordbeurs 377",
          "line": [ "Noordbeurs 377" ],
          "city": "Dauwendaele",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL138-448-293",
      "resource": {
        "resourceType": "Patient",
        "id": "NL138-448-293",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:45:48.289+00:00",
          "source": "#eOvG5vhMG66cfa9I",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL138-448-293"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Elisabeth Schaap",
          "family": "Schaap",
          "given": [ "Elisabeth" ]
        }, {
          "use": "maiden",
          "text": "Elisabeth Schreuder",
          "family": "Schreuder",
          "given": [ "Elisabeth" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "elisabethschaap.56@gmx.net",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 118 949 7272",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 063 730 3911",
          "use": "mobile",
          "rank": 2
        }, {
          "system": "phone",
          "value": "+31 068 848 3100",
          "use": "work",
          "rank": 3
        } ],
        "gender": "female",
        "birthDate": "1953-12-16",
        "address": [ {
          "text": "4336 Middelburg, Raadhuissteeg 115",
          "line": [ "Raadhuissteeg 115" ],
          "city": "Middelburg",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4336",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL976-637-307",
      "resource": {
        "resourceType": "Patient",
        "id": "NL976-637-307",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:46:50.801+00:00",
          "source": "#kOOXrzBRqtAQJ8G2",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL976-637-307"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Nicola de Bruijne",
          "family": "de Bruijne",
          "given": [ "Nicola" ]
        }, {
          "use": "maiden",
          "text": "Nicola Veenstra",
          "family": "Veenstra",
          "given": [ "Nicola" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "nicoladebruijne@yahoo.com",
          "use": "home",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1982-04-04",
        "address": [ {
          "text": "4387 Vlissingen, Langsteeg 407",
          "line": [ "Langsteeg 407" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4387",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL305-939-360",
      "resource": {
        "resourceType": "Patient",
        "id": "NL305-939-360",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:47:53.297+00:00",
          "source": "#wjPWbFP8LPG3l93p",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL305-939-360"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Gunda de Lange",
          "family": "de Lange",
          "given": [ "Gunda" ]
        }, {
          "use": "maiden",
          "text": "Gunda Dieleman",
          "family": "Dieleman",
          "given": [ "Gunda" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "gundadelange@gmx.net",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 068 208 3191",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1979-07-27",
        "address": [ {
          "text": "4341 Arnemuiden, Paleissteeg 716",
          "line": [ "Paleissteeg 716" ],
          "city": "Arnemuiden",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4341",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL651-792-534",
      "resource": {
        "resourceType": "Patient",
        "id": "NL651-792-534",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:48:55.810+00:00",
          "source": "#vXqmqkJz0K18nhSe",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL651-792-534"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Margarete Achterberg",
          "family": "Achterberg",
          "given": [ "Margarete" ]
        }, {
          "use": "maiden",
          "text": "Margarete Valk",
          "family": "Valk",
          "given": [ "Margarete" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "margareteachterberg@yahoo.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 062 637 6753",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1958-10-10",
        "address": [ {
          "text": "4501 Oostburg, Sportsingel 832",
          "line": [ "Sportsingel 832" ],
          "city": "Oostburg",
          "district": "Gemeente Sluis",
          "state": "Zeeland",
          "postalCode": "4501",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL849-139-358",
      "resource": {
        "resourceType": "Patient",
        "id": "NL849-139-358",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:49:58.310+00:00",
          "source": "#Dsjo6YEH7PR42e7H",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL849-139-358"
        } ],
        "active": false,
        "name": [ {
          "use": "official",
          "text": "Gebkea Timmermans",
          "family": "Timmermans",
          "given": [ "Gebkea" ]
        }, {
          "use": "official",
          "text": "Gebkea Timmermans",
          "family": "Timmermans",
          "given": [ "Gebkea" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "gebkeatimmermans@mail.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 063 376 4854",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1968-11-22",
        "address": [ {
          "text": "4336 Middelburg, Langplantsoen 686",
          "line": [ "Langplantsoen 686" ],
          "city": "Middelburg",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4336",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL671-538-262",
      "resource": {
        "resourceType": "Patient",
        "id": "NL671-538-262",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:51:01.004+00:00",
          "source": "#blRlY99PMXEuV2v1",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL671-538-262"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Eliene Schaafsma",
          "family": "Schaafsma",
          "given": [ "Eliene" ]
        }, {
          "use": "official",
          "text": "Eliene Schaafsma",
          "family": "Schaafsma",
          "given": [ "Eliene" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "elieneschaafsma@lycos.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 062 754 2483",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1965-11-10",
        "address": [ {
          "text": "4384 Vlissingen, Zeeplaats 43",
          "line": [ "Zeeplaats 43" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4384",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL662-200-260",
      "resource": {
        "resourceType": "Patient",
        "id": "NL662-200-260",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:52:03.563+00:00",
          "source": "#IxEThUB1aTCDEM4O",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL662-200-260"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Burckhard Chan",
          "family": "Chan",
          "given": [ "Burckhard" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "burckhard.1935@chan.NL",
          "use": "home",
          "rank": 1
        }, {
          "system": "email",
          "value": "burckhardchan.96@outlook.com",
          "use": "home",
          "rank": 2
        }, {
          "system": "phone",
          "value": "+31 062 573 1235",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "male",
        "birthDate": "1935-09-21",
        "address": [ {
          "text": "Dauwendaele, Nieuwebrug 43",
          "line": [ "Nieuwebrug 43" ],
          "city": "Dauwendaele",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL846-977-382",
      "resource": {
        "resourceType": "Patient",
        "id": "NL846-977-382",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:53:06.018+00:00",
          "source": "#VUUQ47GRwDNzVhOs",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL846-977-382"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Marion van der Maas",
          "family": "van der Maas",
          "given": [ "Marion" ]
        }, {
          "use": "official",
          "text": "Marion van der Maas",
          "family": "van der Maas",
          "given": [ "Marion" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "marionvandermaas@yahoo.com",
          "use": "work",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 068 777 1868",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1941-03-24",
        "address": [ {
          "text": "4383 Vlissingen, Dorpsingel 735",
          "line": [ "Dorpsingel 735" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4383",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL101-829-506",
      "resource": {
        "resourceType": "Patient",
        "id": "NL101-829-506",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:54:08.555+00:00",
          "source": "#bz5jAnTvnznRCcal",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL101-829-506"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Jip Chan",
          "family": "Chan",
          "given": [ "Jip" ]
        }, {
          "use": "official",
          "text": "Jip Chan",
          "family": "Chan",
          "given": [ "Jip" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "jipchan@gmail.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 061 275 9957",
          "use": "mobile",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 118 274 5590",
          "use": "work",
          "rank": 2
        } ],
        "gender": "female",
        "birthDate": "1941-02-25",
        "address": [ {
          "text": "4337 Middelburg, Paleisbocht 355",
          "line": [ "Paleisbocht 355" ],
          "city": "Middelburg",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4337",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL910-951-557",
      "resource": {
        "resourceType": "Patient",
        "id": "NL910-951-557",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:55:11.043+00:00",
          "source": "#ZY6K1LEOELsTxyzr",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL910-951-557"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Zwanette van Harten",
          "family": "van Harten",
          "given": [ "Zwanette" ]
        }, {
          "use": "maiden",
          "text": "Zwanette Mulder",
          "family": "Mulder",
          "given": [ "Zwanette" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "zwanettevanharten@mail.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 068 883 7927",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1984-05-16",
        "address": [ {
          "text": "4386 Vlissingen, Dorppad 299",
          "line": [ "Dorppad 299" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4386",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL334-932-491",
      "resource": {
        "resourceType": "Patient",
        "id": "NL334-932-491",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:56:13.536+00:00",
          "source": "#AOgReyN8nHpm1uld",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL334-932-491"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Jann Meijer",
          "family": "Meijer",
          "given": [ "Jann" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "jannmeijer@gmail.com",
          "use": "work",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 062 302 7025",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "male",
        "birthDate": "1948-06-26",
        "address": [ {
          "text": "4341 Arnemuiden, Noordlaan 19",
          "line": [ "Noordlaan 19" ],
          "city": "Arnemuiden",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "postalCode": "4341",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL382-296-372",
      "resource": {
        "resourceType": "Patient",
        "id": "NL382-296-372",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:57:16.023+00:00",
          "source": "#srEBJZR8Eip6zBoX",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL382-296-372"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Ricarda ter Horst",
          "family": "ter Horst",
          "given": [ "Ricarda" ]
        }, {
          "use": "maiden",
          "text": "Ricarda Cheung",
          "family": "Cheung",
          "given": [ "Ricarda" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "ricarda@terhorst.NL",
          "use": "home",
          "rank": 1
        }, {
          "system": "email",
          "value": "ricardaterhorst.7@gmail.com",
          "use": "home",
          "rank": 2
        }, {
          "system": "phone",
          "value": "+31 065 686 8705",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1974-08-22",
        "address": [ {
          "text": "4384 Vlissingen, Molensingel 650",
          "line": [ "Molensingel 650" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4384",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL786-478-185",
      "resource": {
        "resourceType": "Patient",
        "id": "NL786-478-185",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:58:18.529+00:00",
          "source": "#QlIEWTJEOyq6tfRu",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL786-478-185"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Elma van der Valk",
          "family": "van der Valk",
          "given": [ "Elma" ]
        }, {
          "use": "official",
          "text": "Elma van der Valk",
          "family": "van der Valk",
          "given": [ "Elma" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "elmavandervalk@yahoo.com",
          "use": "home",
          "rank": 1
        } ],
        "gender": "female",
        "birthDate": "1969-11-04",
        "address": [ {
          "text": "Klarenbeek, Schoolsteeg 205",
          "line": [ "Schoolsteeg 205" ],
          "city": "Klarenbeek",
          "district": "Gemeente Middelburg",
          "state": "Zeeland",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    }, {
      "fullUrl": "http://hapi.fhir.org/baseR4/Patient/NL551-740-516",
      "resource": {
        "resourceType": "Patient",
        "id": "NL551-740-516",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2020-04-26T04:59:21.061+00:00",
          "source": "#RPsSIgAGruNwIbX1",
          "tag": [ {
            "system": "https://www.graphomed.eu",
            "code": "grmV0.1"
          } ]
        },
        "text": {
          "status": "generated",
          "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated Patient resource for testing purposes. Generated by <a href=\"https://www.graphomed.eu\">graphomed.eu</a></div>"
        },
        "identifier": [ {
          "use": "official",
          "system": "https://info.graphomed.eu/id",
          "value": "NL551-740-516"
        } ],
        "active": true,
        "name": [ {
          "use": "official",
          "text": "Guido van Bruggen",
          "family": "van Bruggen",
          "given": [ "Guido" ]
        } ],
        "telecom": [ {
          "system": "email",
          "value": "guidovanbruggen@yahoo.com",
          "use": "home",
          "rank": 1
        }, {
          "system": "phone",
          "value": "+31 063 401 4183",
          "use": "mobile",
          "rank": 1
        } ],
        "gender": "male",
        "birthDate": "1949-08-25",
        "address": [ {
          "text": "4386 Vlissingen, Schoolweg 81",
          "line": [ "Schoolweg 81" ],
          "city": "Vlissingen",
          "district": "Gemeente Vlissingen",
          "state": "Zeeland",
          "postalCode": "4386",
          "country": "NL"
        } ]
      },
      "search": {
        "mode": "match"
      }
    } ]
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
